# Generated by Django 3.2.4 on 2021-06-26 22:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('idc', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='doc',
            name='name',
            field=models.CharField(default='notes', max_length=15),
        ),
    ]
